### ISSUE TITLE
Tooltip floating near top left of page

### ISSUE THREAD

**Issue by NicholasPhillips** [pleerock/ng2-tooltip#10]
After mousing over a tooltip near the bottom of my page the tooltip displays correctly as pictured below.

![tooltip](https://cloud.githubusercontent.com/assets/5967284/18743779/87ecdd38-80b2-11e6-9050-a99e5f89830c.png)

If i then scroll back up to the top of my page the tooltip seems to be stuck near the top of the page and doesn't disappear. 

![floatingtooltip](https://cloud.githubusercontent.com/assets/5967284/18743840/deee685e-80b2-11e6-9a3c-22ff9d7c0a1c.png)

If i inspect the floating tooltip i get 

div role="tooltip" ng-reflect-class-name="tooltip bottom" class="tooltip bottom in" style="top: -1000px; left: -1000px;"

As you can see the inline style that seems to position the tooltip has gone a little wonky. 
If i mouse over tooltips higher up my page then this issue does not occur.
I cannot currently give a print screen of the full page as it contains company sensitive data.
If there is any code you would like to see then let me know.

**Comment by NicholasPhillips** [comment]
It turns out that after the page becomes a certain length tooltips aren't correctly hidden off the page.

Adding in the css below has fixed the issue for the moment but is not ideal. 
.tooltip.in:not(.fade){
  visibility: hidden;
  left: -99999px !important;
}

**Comment by pleerock** [comment]
Please create a plunker with representation of this problem, so I can where problem is and fix it
