### ISSUE TITLE
Pass data to tooltip-content

### ISSUE THREAD

**Issue by jredd** [pleerock/ng2-tooltip#5]
Is this already possible? I'd like to be able to pass data to the tool-tip template so I can layout multiple lines of data on the tooltip.

**Comment by pleerock** [comment]
what do you mean by passing a data to a tooltip-content? I you want to show some data you just need to put this data inside tooltip-content element. Take a look on samples

**Comment by jredd** [comment]
I should have been more clear. My specific use case is that I have an *ngFor loop and I'm building a list of elements that I'd like to show a tool tip for, with more detailed information on the tip. I'd like to pass the object  to the template with the pertinent data for the tooltip.

**Comment by pleerock** [comment]
if you have a loop then you have two choices: 

* don't use tooltip-content and only use tooltip directive (but you cant use complex html)
* use tooltip-content inside your loop, e.g. individual tooltip-content for each element in your loop

**Comment by pleerock** [comment]
looks like the issue is resolved?
