### ISSUE TITLE
Congratulations !

### ISSUE THREAD

**Issue by samfrach** [pleerock/ng2-tooltip#6]
Hello,

it's not an issue : I am satisfied with your development and thankful for the job.

Where could I find other components like yours ?
There are many components on the web called ng2... but there are buggy or out-of-date...

The idea would be to have a site where components are evaluated and listed.
Do you know about such a site ?

thank you !

**Comment by pleerock** [comment]
Hey, thanks :) You can find other components like mine in the list of my repositories :D I think if you google you'll find some sites where components are listed. I know in reddit/angular2 there is a list of ng2 components. You can always create your own site where you'll list up to date ng2 components ;)
